name: Meshery-Operator CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  golangci-lint:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        go-version: [1.19.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  codecov:
    needs: golangci-lint
    name: Code Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Debug
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request Body: ${{ github.event.pull_request.body }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Run unit tests
        run: go test --short ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: unittests

  build:
    name: Build
    if: |
      github.event_name == 'pull_request' &&
      steps.fetch-comments.outputs.has-lgtm-or-approved == 'true'
    needs: fetch-comments
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Build
        run: make build

  fetch-comments:
    name: Fetch Pull Request Comments
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    outputs:
      has-lgtm-or-approved: ${{ steps.check-comments.outputs.has-lgtm-or-approved }}
    steps:
      - name: Get pull request number
        id: pr_number
        run: echo "::set-output name=number::${{ github.event.pull_request.number }}"
      - name: Fetch comments
        id: check-comments
        run: |
          PR_NUMBER=${{ needs.pr_number.outputs.number }}
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            | jq -r '.[] | select(.created_at > ${{ github.event.pull_request.created_at }}) | .body')
          if echo "$COMMENTS" | grep -iqE '(LGTM|approved)'; then
            echo "::set-output name=has-lgtm-or-approved::true"
          else
            echo "::set-output name=has-lgtm-or-approved::false"
          fi

