name: Meshery-Operator CI

on:
  pull_request:
    branches: [ master ]
    types: [opened, reopened, synchronize]
  push:
    branches: [ master ]
  issue_comment:
    types: [created]

jobs:
  golangci-lint:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        go-version: [1.19.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  codecov:
    needs: golangci-lint
    name: Code Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Debug
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request Body: ${{ github.event.pull_request.body }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Run unit tests
        run: go test --short ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: unittests

  build:
    name: Build on LGTM
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Build
        run: make build
      - name: LGTM Approve
        if: ${{ github.event.issue.pull_request }}
        uses: jonyhy96/lgtm-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          times: 1
          lgtm: 'lgtm'
